name: Release Extension

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      publishMS:
        description: "Publish to the Microsoft Marketplace"
        type: boolean
        required: false
        default: "false"
      publishOVSX:
        description: "Publish to Open VSX"
        type: boolean
        required: true
        default: "true"
      publishGH:
        description: "Publish to GitHub Releases"
        type: boolean
        required: true
        default: "true"

jobs:
  download:
    steps:
      - uses: actions/checkout@v7
      - uses: actions/download-artifact@v8
        with:
          name: ${{ needs.package.outputs.packageName }}
        
  publishMS:
    name: Publish to VS marketplace
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publishMS == 'true'
    steps:
      - name: Publish to VS marketplace
        run: npx vsce publish --packagePath ./${{ needs.package.outputs.packageName }} -p ${{ secrets.VSCE_PAT }}

  publishOVSX:
    name: Publish to Open VSX
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publishOVSX == 'true'
    steps:
      - name: Publish to Open VSX
        run: npx ovsx publish ./${{ needs.package.outputs.packageName }} -p ${{ secrets.OVSX_PAT }}

  publishGH:
    name: Publish to GitHub releases
    runs-on: ubuntu-latest
    needs: package
    if: github.event.inputs.publishGH == 'true'
    steps:
      - name: Upload assets to a Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ needs.package.outputs.packageName }}
          release-tag: ${{ needs.package.outputs.tag }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}